### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#18]
For anyone that wants to do translations, read this first:

https://manual.os-js.org/v3/guide/translate/

Then comment on this issue if you want to join the translation team :nerd_face: 

---

**This section will be updated as translations are added**

Core translations are located in `@osjs/client` within the folder `src/locales/`.

All packages ending with `-application` has a `metadata.json` file which contains application title + description.

These packages have their own expanded sets of translations:

* `@osjs/filemanager-application` - `/locales.js`
* `@osjs/panels` - `/src/locales.js`
* `@osjs/draw-application` - `src/locales.js`

---

Related issues:

* https://github.com/os-js/manual.os-js.org/issues/8

**Comment by andersevenrud** [comment]
@zqqq Can you look translating the default applications ? Just like you did with *Settings* :smile:

**Comment by andersevenrud** [comment]
@zqqq Sorry. I meant just like you did with the core. You can find what files in the description

**Comment by Nerothos** [comment]
I'm working on fr_FR version. I will PR when I'm done.

**Comment by eraffaelli** [comment]
I'm working on a fr_FR version for the packages. I will contct you and PR when done.

**Comment by junland** [comment]
+1 Props for all the translators :)

**Comment by Kirkhammetz** [comment]
I've worked on an it_IT Italian version, I'm opening a pull request and contacting you :)

**Comment by andersevenrud** [comment]
:+1:

**Comment by sieira** [comment]
I'll do the es_ES as soon as I find some time

**Comment by Kirkhammetz** [comment]
Updated it_IT following #289, PR coming soon

**Comment by marktopper** [comment]
Locale `bg_BG` misses:
```
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `no_NO` misses:
```
 - ERR_APP_CONSTRUCT_FAILED_FMT
 - ERR_APP_INIT_FAILED_FMT
 - ERR_APP_PRELOAD_FAILED_FMT
 - ERR_OPERATION_TIMEOUT
 - ERR_OPERATION_TIMEOUT_FMT
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - MSG_SESSION_WARNING
 - BUGREPORT_MSG
 - SERVICENOTIFICATION_TOOLTIP
 - ERR_UTILS_XHR_FATAL
 - ERR_UTILS_XHR_FMT
 - DIALOG_FILE_ERROR_FIND
 - DIALOG_UPLOAD_TOO_BIG
 - DIALOG_UPLOAD_TOO_BIG_FMT
 - WLAPI_INIT_FAILED_FMT
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFS_REMOTEREAD_EMPTY
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_EMPTYTRASH
 - ERR_VFSMODULE_EMPTYTRASH_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - ERR_PACKAGE_EXISTS
 - LBL_STATUS
 - LBL_READONLY
 - LBL_CREATED
 - LBL_MODIFIED
 - LBL_SHOW_COLUMNS
 - LBL_MOVE
 - LBL_OPTIONS
 - LBL_OK
 - LBL_DIRECTORY
 - LBL_CREATE
 - LBL_BUGREPORT
 - LBL_INSTALL
 - LBL_UPDATE
 - LBL_REMOVE
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
```

Locale `de_DE` misses:
```
 - ERR_OPERATION_TIMEOUT
 - ERR_OPERATION_TIMEOUT_FMT
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - MSG_SESSION_WARNING
 - BUGREPORT_MSG
 - SERVICENOTIFICATION_TOOLTIP
 - ERR_UTILS_XHR_FATAL
 - ERR_UTILS_XHR_FMT
 - DIALOG_FILE_ERROR_FIND
 - DIALOG_UPLOAD_TOO_BIG
 - DIALOG_UPLOAD_TOO_BIG_FMT
 - WLAPI_DISABLED
 - WLAPI_SIGN_OUT
 - WLAPI_LOAD_FAILURE
 - WLAPI_LOGIN_FAILED
 - WLAPI_LOGIN_FAILED_FMT
 - WLAPI_INIT_FAILED_FMT
 - ERR_VFS_UNAVAILABLE
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFS_REMOTEREAD_EMPTY
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_XHR_ERROR
 - ERR_VFSMODULE_ROOT_ID
 - ERR_VFSMODULE_NOSUCH
 - ERR_VFSMODULE_PARENT
 - ERR_VFSMODULE_PARENT_FMT
 - ERR_VFSMODULE_SCANDIR
 - ERR_VFSMODULE_SCANDIR_FMT
 - ERR_VFSMODULE_READ
 - ERR_VFSMODULE_READ_FMT
 - ERR_VFSMODULE_WRITE
 - ERR_VFSMODULE_WRITE_FMT
 - ERR_VFSMODULE_COPY
 - ERR_VFSMODULE_COPY_FMT
 - ERR_VFSMODULE_UNLINK
 - ERR_VFSMODULE_UNLINK_FMT
 - ERR_VFSMODULE_MOVE
 - ERR_VFSMODULE_MOVE_FMT
 - ERR_VFSMODULE_EXIST
 - ERR_VFSMODULE_EXIST_FMT
 - ERR_VFSMODULE_FILEINFO
 - ERR_VFSMODULE_FILEINFO_FMT
 - ERR_VFSMODULE_MKDIR
 - ERR_VFSMODULE_MKDIR_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_URL
 - ERR_VFSMODULE_URL_FMT
 - ERR_VFSMODULE_TRASH
 - ERR_VFSMODULE_TRASH_FMT
 - ERR_VFSMODULE_UNTRASH
 - ERR_VFSMODULE_UNTRASH_FMT
 - ERR_VFSMODULE_EMPTYTRASH
 - ERR_VFSMODULE_EMPTYTRASH_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - DROPBOX_NOTIFICATION_TITLE
 - DROPBOX_SIGN_OUT
 - ONEDRIVE_ERR_RESOLVE
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - ERR_PACKAGE_EXISTS
 - LBL_STATUS
 - LBL_READONLY
 - LBL_CREATED
 - LBL_MODIFIED
 - LBL_SHOW_COLUMNS
 - LBL_MOVE
 - LBL_OPTIONS
 - LBL_OK
 - LBL_DIRECTORY
 - LBL_CREATE
 - LBL_BUGREPORT
 - LBL_INSTALL
 - LBL_UPDATE
 - LBL_REMOVE
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `es_ES` misses:
```
 - ERR_OPERATION_TIMEOUT
 - ERR_OPERATION_TIMEOUT_FMT
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - ERR_PACKAGE_EXISTS
 - LBL_DIRECTORY
 - LBL_CREATE
 - LBL_BUGREPORT
 - LBL_INSTALL
 - LBL_UPDATE
 - LBL_REMOVE
 - LBL_SHOW_SIDEBAR
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `fr_FR` misses:
```
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SEARCH
```

Locale `ru_RU` misses:
```
 - ERR_OPERATION_TIMEOUT
 - ERR_OPERATION_TIMEOUT_FMT
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - MSG_SESSION_WARNING
 - BUGREPORT_MSG
 - SERVICENOTIFICATION_TOOLTIP
 - ERR_UTILS_XHR_FATAL
 - ERR_UTILS_XHR_FMT
 - DIALOG_FILE_ERROR_FIND
 - DIALOG_UPLOAD_TOO_BIG
 - DIALOG_UPLOAD_TOO_BIG_FMT
 - WLAPI_DISABLED
 - WLAPI_SIGN_OUT
 - WLAPI_LOAD_FAILURE
 - WLAPI_LOGIN_FAILED
 - WLAPI_LOGIN_FAILED_FMT
 - WLAPI_INIT_FAILED_FMT
 - ERR_VFS_UNAVAILABLE
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFS_REMOTEREAD_EMPTY
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_XHR_ERROR
 - ERR_VFSMODULE_ROOT_ID
 - ERR_VFSMODULE_NOSUCH
 - ERR_VFSMODULE_PARENT
 - ERR_VFSMODULE_PARENT_FMT
 - ERR_VFSMODULE_SCANDIR
 - ERR_VFSMODULE_SCANDIR_FMT
 - ERR_VFSMODULE_READ
 - ERR_VFSMODULE_READ_FMT
 - ERR_VFSMODULE_WRITE
 - ERR_VFSMODULE_WRITE_FMT
 - ERR_VFSMODULE_COPY
 - ERR_VFSMODULE_COPY_FMT
 - ERR_VFSMODULE_UNLINK
 - ERR_VFSMODULE_UNLINK_FMT
 - ERR_VFSMODULE_MOVE
 - ERR_VFSMODULE_MOVE_FMT
 - ERR_VFSMODULE_EXIST
 - ERR_VFSMODULE_EXIST_FMT
 - ERR_VFSMODULE_FILEINFO
 - ERR_VFSMODULE_FILEINFO_FMT
 - ERR_VFSMODULE_MKDIR
 - ERR_VFSMODULE_MKDIR_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_URL
 - ERR_VFSMODULE_URL_FMT
 - ERR_VFSMODULE_TRASH
 - ERR_VFSMODULE_TRASH_FMT
 - ERR_VFSMODULE_UNTRASH
 - ERR_VFSMODULE_UNTRASH_FMT
 - ERR_VFSMODULE_EMPTYTRASH
 - ERR_VFSMODULE_EMPTYTRASH_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - DROPBOX_NOTIFICATION_TITLE
 - DROPBOX_SIGN_OUT
 - ONEDRIVE_ERR_RESOLVE
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - ERR_PACKAGE_EXISTS
 - LBL_STATUS
 - LBL_READONLY
 - LBL_CREATED
 - LBL_MODIFIED
 - LBL_SHOW_COLUMNS
 - LBL_MOVE
 - LBL_OPTIONS
 - LBL_OK
 - LBL_DIRECTORY
 - LBL_CREATE
 - LBL_BUGREPORT
 - LBL_INSTALL
 - LBL_UPDATE
 - LBL_REMOVE
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `ko_KR` misses:
```
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SEARCH
```

Locale `zh_CN` misses:
```
 - ERR_OPERATION_TIMEOUT
 - ERR_OPERATION_TIMEOUT_FMT
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - MSG_SESSION_WARNING
 - BUGREPORT_MSG
 - SERVICENOTIFICATION_TOOLTIP
 - ERR_UTILS_XHR_FATAL
 - ERR_UTILS_XHR_FMT
 - DIALOG_FILE_ERROR_FIND
 - WLAPI_INIT_FAILED_FMT
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFS_REMOTEREAD_EMPTY
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - ERR_PACKAGE_EXISTS
 - LBL_CREATED
 - LBL_MODIFIED
 - LBL_SHOW_COLUMNS
 - LBL_MOVE
 - LBL_OPTIONS
 - LBL_OK
 - LBL_DIRECTORY
 - LBL_CREATE
 - LBL_BUGREPORT
 - LBL_INSTALL
 - LBL_UPDATE
 - LBL_REMOVE
 - LBL_SHOW_SIDEBAR
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `nl_NL` misses:
```
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SEARCH
```

Locale `pl_PL` misses:
```
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `pt_BR` misses:
```
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SHOW_SIDEBAR
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `sk_SK` misses:
```
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `vi_VN` misses:
```
 - ERR_NO_SESSION
 - MSG_SESSION_WARNING
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
```

Locale `tr_TR` misses:
```
 - ERR_ARGUMENT_FMT
 - ERR_LOGIN_FMT
 - ERR_LOGIN_INVALID
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_INVALID
 - ERR_VFSMODULE_INVALID_FMT
 - ERR_VFSMODULE_INVALID_METHOD
 - ERR_VFSMODULE_INVALID_METHOD_FMT
 - ERR_VFSMODULE_INVALID_TYPE
 - ERR_VFSMODULE_INVALID_TYPE_FMT
 - ERR_VFSMODULE_INVALID_CONFIG
 - ERR_VFSMODULE_INVALID_CONFIG_FMT
 - ERR_VFSMODULE_ALREADY_MOUNTED
 - ERR_VFSMODULE_ALREADY_MOUNTED_FMT
 - ERR_VFSMODULE_NOT_MOUNTED
 - ERR_VFSMODULE_NOT_MOUNTED_FMT
 - ERR_VFSMODULE_EXCEPTION
 - ERR_VFSMODULE_EXCEPTION_FMT
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - ZIP_PRELOAD_FAIL
 - ZIP_VENDOR_FAIL
 - ZIP_NO_RESOURCE
 - ZIP_NO_PATH
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SHOW_NAVIGATION
 - LBL_SHOW_HIDDENFILES
 - LBL_SHOW_FILEEXTENSIONS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `it_IT` misses:
```
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_SEARCH
```

Locale `fa_FA` misses:
```
 - ERR_ARGUMENT_FMT
 - ERR_NO_SESSION
 - DIALOG_FILE_ERROR_FIND
 - ERR_VFS_TARGET_NOT_EXISTS
 - ERR_VFSMODULE_NOT_FOUND_FMT
 - ERR_VFSMODULE_READONLY
 - ERR_VFSMODULE_READONLY_FMT
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
 - ERR_VFSMODULE_FIND
 - ERR_VFSMODULE_FIND_FMT
 - ERR_VFSMODULE_FREESPACE
 - ERR_VFSMODULE_FREESPACE_FMT
 - ERR_VFSMODULE_EXISTS
 - ERR_VFSMODULE_EXISTS_FMT
 - SEARCH_LOADING
 - SEARCH_NO_RESULTS
 - LBL_MOUNT
 - LBL_DESCRIPTION
 - LBL_USERNAME
 - LBL_PASSWORD
 - LBL_HOST
 - LBL_NAMESPACE
 - LBL_SEARCH
```

Locale `ar_DZ` misses:
```
 - ERR_VFSMODULE_MKFILE
 - ERR_VFSMODULE_MKFILE_FMT
```

This snippet created by using this [script](https://gist.github.com/marktopper/08891010238e152553a8fb02ffc4bb8f) in the console.

**Comment by Kirkhammetz** [comment]
Added the missing it_IT in #493 
Fixed a small english typo in #494

**Comment by andersevenrud** [comment]
@Kirkhammetz :+1:

**Comment by marktopper** [comment]
Just updated my [comment above](#issuecomment-248831858) with the current missing language strings.

**Comment by andersevenrud** [comment]
@marktopper Nice :) I just made a commit with the missing `no_NO` ones. Also includes the new stuff coming in next update.

For anyone else interested you can see everything starting from this line https://github.com/os-js/OS.js/blob/eaa145cb9fd57d19a86e5ae462cb884b10a6d0ce/src/client/javascript/locales/no_NO.js#L413

**Comment by marktopper** [comment]
@andersevenrud: Just updated my [comment above](https://github.com/os-js/OS.js/issues/18#issuecomment-248831858).

**Comment by andersevenrud** [comment]
@marktopper With the recent update, some more stuff has been added. If you feel like it you can update the lists :)

**Comment by marktopper** [comment]
@andersevenrud, sorry for the waiting. Updated the list, nice work with the new implementations.

**Comment by andersevenrud** [comment]
@marktopper No worries. I don't put up any expectations on stuff like this :)

**Comment by marktopper** [comment]
Updated missing strings list for #508

**Comment by andersevenrud** [comment]
*--- Calling all translators ---*

If anyone is up for translation of v3 stuff, please let me know :)

**Comment by JamesZEMOURI** [comment]
@andersevenrud i am up to

**Comment by frju365** [comment]
I'm ok to translate into French, Portuguese and German.

**Comment by andersevenrud** [comment]
@frju365 Your French translations have now been published across all packages that you made a PR. Thanks!

As a side-node, I've updated the "description" in the metadata files to be a bit more descriptive, so maybe you can look at that ?

Also, I've updated the manual about translating packages:


https://manual.os-js.org/v3/guide/translate/

**Comment by filips123** [comment]
@andersevenrud I can translate to Slovenian.
What should be translated in v3?

**Comment by andersevenrud** [comment]
@filips123 Nice :)

See:

* https://github.com/os-js/osjs-client/tree/master/src/locale
* https://github.com/os-js/osjs-panels/blob/master/src/locales.js
* The `metadata.json` files in the applications + themes

**Comment by filips123** [comment]
@andersevenrud I created PRs os-js/osjs-client#18 and os-js/osjs-panels#6. I will translate other application and themes later.

**Comment by filips123** [comment]
I created few more PRs (os-js/osjs-client#26, os-js/osjs-freedesktop-sounds#2, os-js/osjs-gnome-icons#2, os-js/osjs-standard-dark-theme#2, os-js/osjs-standard-theme#4). I will translate applications later when they become almost finished because they could maybe be changed until stable v3.

You should remove milestone 2.2.0 from this issue 😃.

**Comment by OlivieBright** [comment]
How can I help translate?

**Comment by SpaceboyRoss01** [comment]
Look at applications and modules that don't have translations for languages you know and then fork and add the translations and send a pull request.

**Comment by andersevenrud** [comment]
@OlivieBright 

See https://manual.os-js.org/v3/guide/translate/ for a guide on how translation works.

Then look at https://manual.os-js.org/v3/resource/official/ for a list of core modules and applications that can be translated (almost all of them have localization in them)

**Comment by filips123** [comment]
You should post message every time when it is need to translate new thing.

**Comment by andersevenrud** [comment]
@filips123 Yeah. I'm planning on making a routine script that pulls all the diffs for locale changes and posts them here every two weeks or something.

**Comment by andersevenrud** [comment]
@filips123 I've updated the top comment to contain a list of packages which have translations of their own. I'll see if I can't get this automated script running before newyears.

**Comment by BoFFire** [comment]
Hello :)
I came here via Mastodon. I want to help to translate OS-JS to arabic. Thank you for this awesome project :)

**Comment by andersevenrud** [comment]
@BoFFire Hi!

Nice! Translations are always welcome :)

Instructions are in the top comment. If anything is unclear, let me know.

**Comment by BoFFire** [comment]
Hi @andersevenrud yes :)
I'll try to find a convenient way to make part of translation easier as I'm used to work with .po gettext files and file formats like that.
It's a bit different when we translate in an RTL language ;) but I'm sticking with the project, no problem. First translations will be pushed soon :)

**Comment by andersevenrud** [comment]
@frju365 This list does not currently has the application localization files -- these are only in the top comment at the moment. So you might wanna check those as well.

I'll update my script to locate these files as well, then share it on gist -- then set up an automated bot for it :)

**Comment by andersevenrud** [comment]
@BoFFire It just dawned on me, but I have to add support for RTL CSS styles. I've opened an issue on this and will fix for next publish :nerd_face: 

https://github.com/os-js/osjs-client/issues/38

**Comment by filips123** [comment]
Maybe it will be better to use some localisation platform (eg. Transifex, Crowding...) instead of just files that are edited. It will be easier to track for changes and untranslated strings

**Comment by andersevenrud** [comment]
Yes -- I wrote that my local repos might not be up to date, and that I'll
fix this with an automated setup of sorts.

**Comment by filips123** [comment]
What about some localisation platform? It would be easier to track for changes and untranslated strings.

**Comment by andersevenrud** [comment]
What kind of platform? I'm all for making things easier -- as long as it
won't be an expense. If I actually had any revenue on this project I could
pay up -- but as of now it needs to be either free or some FOSS stuff.

**Comment by filips123** [comment]
There are some free options (with some limitations) available.
Both Transifex and and Crowdin have some free plan for open source projects. I know and use both but I don't know which would be the best. Transifex has organizations feature so it may be better for large projects.

**Comment by andersevenrud** [comment]
I'll do some investegation on this. Thanks!

**Comment by BoFFire** [comment]
Hi @filips123, I'm totally against using Transifex because (…) it's another subject. I prefer Weblate which is Free and Open Source and supports pull, fetch, commit from/to Github/Gitlab

**Comment by andersevenrud** [comment]
@BoFFire Weblate looks pretty nice (FOSS is a big one), but does not seem to have support for custom formats. However, it can read JSON files -- so maybe the `.js` should be converted to that instead. Not sure yet... Looking at some alternatives first.

**Comment by BoFFire** [comment]
Ping @nijel

**Comment by nijel** [comment]
Indeed `.js` is not supported by Weblate. The problem with that is that parsing `.js` files would be always incomplete as it would support only subset of the language. Similarly like we already have with `.php` files - people always want to add support for yet another way to express translations. If somebody contributes it, I have no problem with accepting it though.

However I'd really recommend to stick with some standard way to store translations and use that. There is already [lot of supported formats](https://docs.weblate.org/en/latest/formats.html#translation-types-capabilities).

**Comment by filips123** [comment]
I think you should use some standard and portable format, maybe JSON because it probably won't be hard to convert JS to it.
You should use some format that supports custom plurals (and not just zero, one and more) because some languages (eg. Slovenian) use very complicated ways for plural. It should probably support something like [CLDR](http://www.unicode.org/cldr/charts/27/supplemental/language_plural_rules.html).

You could probably use [JSON i18next files](https://docs.weblate.org/en/latest/formats.html#js-i18next).

**Comment by andersevenrud** [comment]
@nijel Thanks. In this case my `.js` files basically just are flat JSON so I'll look into converting it. 

@filips123 Yup. I was reading on i18next when I was browsing the Weblate documentation. Seems like it should be pretty trivial to make use of that :)

**Comment by andersevenrud** [comment]
@filips123 I'm now actually contemplating adding support for callbacks in the localization that OS.js uses so that it is possible to perform all kinds of actions to any given translation. Example:

```javascript
const some_LANGUAGE = {
  // _('COUNT_FLAT', 0)
  COUNT_FLAT: 'Showing {0} object(s)',

  // _('COUNT_KEY', {count: 0})
  COUNT_KEY: 'Showing {count}',

  // _('COUNT_DYNAMIC_FLAT', 0)
  COUNT_DYNAMIC_FLAT: (count) => count === 1
    ? `Showing {0} object`, 
    : `Showing {0} objects`,

  // _('COUNT_DYNAMIC_KEY', {count: 0})
  COUNT_DYNAMIC_KEY: ({count}) => count === 1
    ? `Showing {count} object`, 
    : `Showing {count} objects`
};
```

This of course won't make it possible to make any of the ready solutions discussed for managing translations (unless you can write support via plugins), but it will make it very easy to implement proper plurals, formatting, interpolations etc. into the current system without introducing any overhead (most of the localization libraries are 20%+ the total size of the OS.js client codebase).

Thoughts ? :)

**Comment by andersevenrud** [comment]
Just an addition to my latest comment I'm prototyping an interface here: https://codepen.io/andersevenrud/pen/PXQRNe

**Comment by filips123** [comment]
I think it would be OK for now but in the future it could be hard to implement this for all pluralisation rules for all languages [CLDR](http://www.unicode.org/cldr/charts/27/supplemental/language_plural_rules.html).

Maybe you could find some lightweight i18next compatibile library or build your own 🤔

**Comment by filips123** [comment]
@andersevenrud For your interface, you should show progress bar for each language separately and table with missing keys should also be separate for each language. This is because translators probably won't care for other translations and their status. This could maybe be done with some tabs or tables.
There should also be link for each missing key to it's original in English ([example](https://github.com/os-js/osjs-client/blob/master/src/locale/en_EN.js#L55)). This would help translators to find where is that key and what should be it's value.

**Comment by filips123** [comment]
@andersevenrud I saw that you updated UI for translations. It is OK but I have few suggestions.

---

Keys are displayed in table with columns "Key", "Translation". What is this "Translation" column. If i is for adding translations, it should probably not be there because translations should be added with editing files (editing from UI would probably be very hard to implement). Also, there sould be column "Original" with link to original translation in English or even direct value of it.

---

Keys are now seperated between languges. This is good, but it is still not so easy to navigate between them.
I think that page should be seperated into tabs ([example of tabs](https://www.w3schools.com/howto/howto_js_tabs.asp)).
First tab could be "Overview" and it could show overview of translations for all package. So for each package, there should be progress bar to show translations for whole package and additional progress bars for each package (like in current UI version). Keys should not be displayed.
For each language, there should be tab with language name. There should be progress bar for translation status of all packages. And then, the translation status should be displayed for each package (like in current UI version but only for one language). It should display package name, progress bar and missing keys with liks to original English value.

---

If possible, languages should be named like "Language name (language-code)". You could use some libraries that convert code to name if they aren't so heavy. Maybe you could also do your library or even don't display language name.

---

There are some libraries for localisation (also for language naming, pluralisation, numbering, displaying dates) but they are probably very heavy. Maybe you can look to some of them and "extract" only functions that are needed here.

**Comment by andersevenrud** [comment]
> Keys are displayed in table with columns "Key", "Translation". What is this "Translation" column. If i is for adding translations, it should probably not be there because translations should be added with editing files (editing from UI would probably be very hard to implement). 

Yes, the translation column was intended for entering a translation. The idea here was that it maybe could be possible to generate code you could copy/paste into the actual sources.

> Also, there sould be column "Original" with link to original translation in English or even direct value of it.

The latter was what I was thinking, with some sort of indication with colors or something.

> This is good, but it is still not so easy to navigate between them.

Haven't really though of this yet, but just using dropdowns might suffice ? `[ package ] [ language ]`

> If possible, languages should be named like "Language name (language-code)".

Can just use some JSON dump found online.

> There are some libraries for localisation (also for language naming, pluralisation, numbering, displaying dates) but they are probably very heavy. Maybe you can look to some of them and "extract" only functions that are needed here.

Yes, this has been discussed above. Dates is already covered, so the main part missing here is proper pluralization.

This can be solved in many ways, but using the suggestions I've made above there won't be any need tor an existing library (and you get more than pluralization to boot), but it's now no longer plain text. I guess this could be solved with some custom string format though...

As for which direction to go, I'm not 100% sure yet.


---

Btw, if you're up for

**Comment by andersevenrud** [comment]
@filips123 

If you're up for some UI prototyping and have some time to kill, feel free to have a look at the UI stuff :)

**Comment by filips123** [comment]
@andersevenrud I'm not familiar with HyperApp but I will try to do something :) Maybe I could also help you with designing backend for the interface. Maybe it could be just client side JavaScript so it could be hosted on GitHub pages.

**Comment by andersevenrud** [comment]
@filips123 Doesn't have to be Hyperapp. I just went for that because it's easy to prototype stuff with it.

As for backend, it's not really required i think. We can just generate a JSON with all of the data and statistics from the repositories -- so some batch job or something.

**Comment by matheusfelipeog** [comment]
@andersevenrud, how can i help translate to portuguese(brazil) and What should be translated in v3?

**Comment by andersevenrud** [comment]
@matheusfelipeog Hi!

If you look at the description of this issue you'll find basic instructions on how to do this.

Basically, these are the files that contain translations:

* https://github.com/os-js/osjs-client/tree/master/src/locale
* https://github.com/os-js/osjs-panels/blob/master/src/locales.js
* https://github.com/os-js/osjs-filemanager-application/blob/master/locales.js
* https://github.com/os-js/osjs-draw-application/blob/master/src/locales.js

What you need to do is to:

1. Clone these repositories
2. Create a new branch in these repos (ex: `git checkout -b feature/portoguese-translation`)
3. Modify the files needed for translations
4. Commit the changes and push to your cloned github repository
5. Create a pull request that I will approve and merge into the official codebase

If you have any further questions about this you can join the official chat https://gitter.im/os-js/OS.js (as to not make this issue long)

**Comment by andersevenrud** [comment]
@matheusfelipeog 

> Clone these repositories

What I meant was to **fork** these repositories on Github.

**Comment by andersevenrud** [comment]
@matheusfelipeog Also, FYI, the following repositories have a `name` and `description` field in the `metadata.json` file that also has translations in them.

* https://github.com/search?q=org%3Aos-js+is%3Aopen+-application&type=Repositories
* https://github.com/search?q=org%3Aos-js+is%3Aopen+-theme&type=Repositories

**Comment by Yutyo** [comment]
I am working on tr_TR translations. Will make a PR when its done.

**Comment by andersevenrud** [comment]
@Yutyo Great! Thanks :)

**Comment by Yutyo** [comment]
@andersevenrud here they are: #149

**Comment by andersevenrud** [comment]
@Yutyo Could you translate the other packages as well (noted in OP) ? Then I could merge all changes at once and release it with complete translations. The client package only covers general messages.

**Comment by Yutyo** [comment]
> @Yutyo Could you translate the other packages as well (noted in OP) ? Then I could merge all changes at once and release it with complete translations. The client package only covers general messages.

Done:
* https://github.com/os-js/osjs-filemanager-application/pull/32
* https://github.com/os-js/osjs-panels/pull/40
* https://github.com/os-js/osjs-draw-application/pull/10

**Comment by andersevenrud** [comment]
@Yutyo Much appreciated :) I've released new builds of all the changes.

**Comment by Yutyo** [comment]
@andersevenrud I see that some important parts are missing in all translations.
![image](https://user-images.githubusercontent.com/40173707/112795445-2f0cbc00-9071-11eb-8eb5-6b11c9522a43.png)

**Comment by andersevenrud** [comment]
@yutyo Should be fixed now. I didn't see that you forgot a step that is noted in the manual. Published a new release of the client.

**Comment by yutyo** [comment]
> @yutyo Should be fixed now. I didn't see that you forgot a step that is noted in the manual. Published a new release of the client.

I have even cloned the repo and did setup from scratch, but its still the same. I guess there are more stuff to translate, cuz the same applies to all other translations.

**Comment by yutyo** [comment]
> @yutyo Not sure what you mean here ? It's not working for you after the latest update?

It works as I have shown in the ss. As you can see, there are more translations to be done that you haven't stated in the thread, guessing from all translations missing parts.

**Comment by andersevenrud** [comment]
@yutyo 

> As you can see, there are more translations to be done that you haven't stated in the thread, guessing from all translations missing parts.

To me it looks like you're missing the client locales there, which you already translated. And on my end it works prefectly fine.

> I have even cloned the repo and did setup from scratch, but its still the same.

Maybe it's just because you're not using the upstream source code then.

**Comment by yutyo** [comment]
> Maybe it's just because you're not using the upstream source code then.

@andersevenrud oh alright. You are right. Sorry, lol.

**Comment by lentas1** [comment]
link broken

**Comment by andersevenrud** [comment]
@lentas1 https://manual.os-js.org/guide/translate/
