### ISSUE TITLE
[Handler] mysql throws "Cannot enqueue Query after fatal error"

### ISSUE THREAD

**Issue by aminmazi** [os-js/OS.js#338]
hi, i wanted to enable multi-user environment with mysql, i did everything same as tutorial [here ](https://github.com/os-js/OS.js/blob/master/doc/mysql-handler.md) but after trying to login with user,user an error dialog appears as: 

```
APIUser::login()
Error: Cannot enqueue Query after fatal error.
```
how can i solve this problem?

**Comment by andersevenrud** [comment]
@ht68 also got this. I will investegate this

**Comment by andersevenrud** [comment]
I am not able to reproduce this. Are you on Windows ?

**Comment by ht68** [comment]
Yes, I'm work on Windows.

**Comment by andersevenrud** [comment]
I'll have to set up a Windows Virtual Machine and find a workaround for this. I know what the problem *is*, but not exactly *why* (weird that it is platform spesific)

**Comment by andersevenrud** [comment]
note-to-self: https://github.com/felixge/node-mysql#pooling-connections

**Comment by aminmazi** [comment]
I'm on windows too,  using wamp server for MySQL and nodejs 32 bit for os.js backend server.
I will try on a Linux machine tomorrow.

**Comment by andersevenrud** [comment]
OK. Thanks for the information. I don't think I have time to solve this today, but I will definately do it by tomorrow.

**Comment by ht68** [comment]
I'm try on centOS tomorrow too and state the feedbacks coming.

**Comment by ht68** [comment]
the problem is still exist on linux !

```
2016-02-16T08:39:40.931Z <<< /API/login
APIUser::login()
Error: Cannot enqueue Query after fatal error.
```

**Comment by andersevenrud** [comment]
Sorry for not getting back to you guys, I've been extremely busy.

I have a possible solution for this in the works and will commit tomorrow

**Comment by andersevenrud** [comment]
Allright boys! I've updated the codebase with a possible fix. Could you test it ? :)

**Comment by aminmazi** [comment]
OK, I will test it tomorrow :)

**Comment by aminmazi** [comment]
the log in works and the error is gone, but multi-user features does not work and current user is still "demo"! (even after logging in with admin admin)
for example I logged in with admin and create a file on home directory, but the new file was created in "demo" folder in vfs.

**Comment by andersevenrud** [comment]
@aminmazi Then it sounds like a broken configuration file. Could you please give me the contents of your `src/conf/900-custom.json` file? 


This happened in #335 as well. To summarize: I made a mistake in the documentation, leading to misconfigured file (the 900-custom file is generated when you do `grunt:config:set`).

So the easiest way to fix this problem is to remove that file and re-do the configuration steps.

**Comment by andersevenrud** [comment]
@ht68 Can you test this as well ? :)

**Comment by aminmazi** [comment]
the problem was solved but there are two considerations:
1) if mysql service does not work (not started for example) the log in page doesn't show any error and enters with demo user.(in my last [problem](https://github.com/os-js/OS.js/issues/338#issuecomment-186575931) I have forgotten to start mysql service )

2) if mysql password has been set as a number  (for example 123456) an error occurred while logging in.
i changed mysql pass to some string and multi-user environment works good now.

**Comment by andersevenrud** [comment]
@aminmazi 

1) The login will return error message if the mysql service is not started/runninig or operating properly. I have just tested this.

If you get the "logged in as demo" problem, the client config is broken (which I explained) and it uses the wrong handler. Which probably means your `src/conf/900-custom.json` is messed up.

https://github.com/os-js/OS.js/issues/335#issuecomment-183521506


2) Fixed in 4ee6db9d622f5ae25221d7228be227ac3404a244

**Comment by aminmazi** [comment]
:+1:

**Comment by andersevenrud** [comment]
@anmonteiro I just realized something..... If you are using `dist` and getting "logged in as demo" even when running the mysql handler, then maybe you forgot to run `grunt core` to update the client properly. If you encounter this problem again, please let me know.

But nice that you got it working at least :)

**Comment by ht68** [comment]
@andersevenrud yes it's solved :+1:

**Comment by andersevenrud** [comment]
Great! :)
