### ISSUE TITLE
Logout, Change Wallpaper

### ISSUE THREAD

**Issue by Amjad121092** [os-js/OS.js#445]
Hi,

I've been testing OS.js and found some issues.

Logout:
When you sign out it throws the following error:

http://127.0.0.1:8000/packages/default/CoreWM/animations.css
> You have no OS.js Session, please log in!

Change Wallpaper:
When you click the file open button to choose a wallpaper it freezes and throws the following error.

windowmanager.js:557 WindowManager::addWindow() => Window::init() TypeError: Cannot read property 'root' of undefined(…) TypeError: Cannot read property 'root' of undefined
    at Object.getRootFromPath (http://127.0.0.1:8000/client/javascript/mount-manager.js:464:32)
    at FileDialog.init (http://127.0.0.1:8000/client/javascript/dialogs/file.js:218:23)
    at Process.WindowManager.addWindow (http://127.0.0.1:8000/client/javascript/windowmanager.js:555:9)
    at Window._addChild (http://127.0.0.1:8000/client/javascript/window.js:1107:10)
    at Object._apiCreateDialog [as createDialog] (http://127.0.0.1:8000/client/javascript/api.js:1224:17)
    at UIElement.<anonymous> (http://127.0.0.1:8000/packages/default/Settings/main.js:268:13)
    at HTMLElement.mouseEventHandler (http://127.0.0.1:8000/client/javascript/utils/events.js:446:18)
    at http://127.0.0.1:8000/client/javascript/gui/inputs.js:825:12
    at HTMLButtonElement.mouseEventHandler (http://127.0.0.1:8000/client/javascript/utils/events.js:446:18)

**Comment by andersevenrud** [comment]
The first error is not a problem, really, but the second issue has been fixed.

Thanks!

**Comment by andersevenrud** [comment]
err... now it is fixed!

**Comment by Amjad121092** [comment]
Hi,

When you perform a logout the screen goes all weird with text overlaying each other.

It throws an actual error:

GET http://127.0.0.1:8000/packages/default/CoreWM/animations.css OSjs.Utils.$createCSS @ dom.js:316CoreWM.setAnimationLink @ main.js:1013CoreWM.setTheme @ main.js:930CoreWM.applySettings @ main.js:827CoreWM.destroy @ main.js:246(anonymous function) @ process.js:111doKillAllProcesses @ process.js:109OSjs.API.shutdown @ init.js:707(anonymous function) @ api.js:1552(anonymous function) @ handler.js:226onsuccess @ handler.js:452onReadyStateChange @ xhr.js:109
Navigated to http://127.0.0.1:8000/

Regards

**Comment by andersevenrud** [comment]
> When you perform a logout the screen goes all weird with text overlaying each other.

That is because the stylesheets are unloaded

> It throws an actual error:

Yes, but it's not a bug. When you lose your session the server will respond with an error for certain resources since they require an active session. So more of a warning, really

**Comment by Amjad121092** [comment]
Thanks for clarifying also i just pulled you changes and the error still exists.

windowmanager.js:557 WindowManager::addWindow() => Window::init() TypeError: Cannot read property 'root' of undefined(…) TypeError: Cannot read property 'root' of undefined
    at Object.getRootFromPath (http://127.0.0.1:8000/client/javascript/mount-manager.js:463:65)
    at FileDialog.init (http://127.0.0.1:8000/client/javascript/dialogs/file.js:218:23)
    at Process.WindowManager.addWindow (http://127.0.0.1:8000/client/javascript/windowmanager.js:555:9)
    at Window._addChild (http://127.0.0.1:8000/client/javascript/window.js:1107:10)
    at Object._apiCreateDialog [as createDialog] (http://127.0.0.1:8000/client/javascript/api.js:1224:17)
    at UIElement.<anonymous> (http://127.0.0.1:8000/packages/default/Settings/main.js:268:13)
    at HTMLElement.mouseEventHandler (http://127.0.0.1:8000/client/javascript/utils/events.js:446:18)
    at http://127.0.0.1:8000/client/javascript/gui/inputs.js:825:12
    at HTMLButtonElement.mouseEventHandler (http://127.0.0.1:8000/client/javascript/utils/events.js:446:18)

**Comment by andersevenrud** [comment]
Try to pull again. I had to make two commits to fix this issue, maybe you got the first one only.

I can confirm it has been fixed

**Comment by andersevenrud** [comment]
@Amjad121092 Is it resolved ?

**Comment by Amjad121092** [comment]
Hi,

I just tried it again and i can confirm i can have latest commit as well but the error still persists.

Regards

**Comment by andersevenrud** [comment]
Try to clear your browser cache.

Do you get the error on https://osjsv2.0o.no/ ? It is running latest code as well

**Comment by Amjad121092** [comment]
Hi,

On your version is seems to be working no idea what i did as mine is still broken. Thanks anyways for all the help! I have the latest code from yours but mine refuses to work hmm...

Regards

**Comment by Amjad121092** [comment]
Hi,

Just installed a fresh copy and it's working perfectly.

Thank you

**Comment by andersevenrud** [comment]
Great!
